import type { Metadata } from "next";

import "./globals.css";
import { MantineProvider } from '@mantine/core';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body>
        <MantineProvider
          theme={{
            fontFamily: 'var(--font-satoshi), -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif',
            headings: {
              fontFamily: 'var(--font-satoshi), -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif',
            },
          }}
        >
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}